language: generic
sudo: required
services:
        - docker

before_install:
        - docker build -t austanin-git/docker-react -f Dockerfile.dev .

script:
        - docker run -e CI=true austanin-git/docker-react npm run test
